services:
  postgres:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "7800:5432"
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: storm_test
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "7801:3306"
